### ISSUE TITLE
Write access?

### ISSUE THREAD

**Issue by ttimbers** [workflows-for-all/sdss-2019#2]
@mikelove - can you please give me write access to this repo? @stephaniehicks - do you need this too?

**Comment by mikelove** [comment]
I think you just need to click approve from the invitation email 

![Screen Shot 2019-05-29 at 4 46 54 PM](https://user-images.githubusercontent.com/69203/58590148-7174d000-8231-11e9-9328-8c1c09864749.png)

**Comment by ttimbers** [comment]
Ah! I only did this for the org and forgot to for the repo! Sorry!!!
